#!/usr/bin/env bash
# sets the webserver with a custom header
# shellcheck disable=SC2154
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | tee /var/www/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/jesulayomy permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/^\tlocation \/ {/\tlocation \/ {\n\t\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/sites-available/default
service nginx restart
